Enable USB gadgets for x86
VfN-NRW/gluon-sites pull request #5
Opened 2017-06-18 14:36 UTC by kaechele

Also change site.mk so that it diffs nicely with upstream sample file
by:
  - sorting package names alphabetically, where dep chain allows
  - removing redundant packages that are implicitly required

Signed-off-by: Felix Kaechele <felix@kaechele.ca>

2017-06-18 15:03 UTC, RubenKelevra requested changes

2017-06-18 15:03 UTC, RubenKelevra commented on gluon10/all/site.mk
> +DEFAULT_GLUON_RELEASE := 4.2.1+exp$(shell date '+%Y%m%d')
Das Default-Release wird bei uns woanders gesetzt, bitte hier nicht definieren

2017-06-18 15:03 UTC, RubenKelevra commented on gluon10/all/site.mk
> +	gluon-status-page \
Die Statusseite ist unnötigerweise dabei

2017-06-18 15:03 UTC, RubenKelevra commented on gluon10/all/site.mk
> +	gluon-ebtables-filter-multicast \
Die Multicast-Filter sind neu dabei, hat das einen Grund warum du die setzt?

2017-06-18 19:40 UTC, kaechele commented
Fixed

2017-06-19 16:42 UTC, RubenKelevra approved these changes

2017-06-19 16:42 UTC, merged